import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "what-it-ships",
      h2: "What does an authority HVAC website actually ship?",
      navLabel: "What it ships",
      speakable: true,
      blocks: [
        { kind: "p", text: "An authority HVAC website ships a **real page for every service in every town you cover**, plus the tools and answers a homeowner types before they ever know your name. AC installation, furnace replacement, heat pump conversion, ductwork, emergency no-cool and no-heat calls, indoor air quality, mini-splits, maintenance plans: each one becomes its own page, crossed with each city you serve. That is the difference between a site that describes your company and a site that **is** the answer Google returns." },
        { kind: "p", text: "A typical HVAC brochure ships around **10 pages**. Our live reference build ships **176**." },
        { kind: "p", text: "That is not a tweak to the same kind of site. It is a different category." },
        { kind: "p", text: "Ten pages can match maybe ten kinds of search: your company name, your home city, a generic services page. The other hundreds of searches, the ones where a homeowner types a problem and a town instead of your name, land on the contractor who built the page. Most of the time that is not you, because the page that would have caught them was never built." },
        { kind: "p", text: "None of this is decoration. A brochure can be beautiful and still lose, because the loss happens under the surface where the homeowner never looks: in the queries the site can match, the facts machines can read, the speed that decides whether anyone stays." },
        { kind: "p", text: "An authority HVAC site is built so a search engine reads it as the single most relevant answer to a heating-and-cooling problem in a specific town, and an AI engine can quote it cleanly. The brochure is read as one business card." },
        { kind: "takeaway", text: "A brochure **describes** your HVAC company. An authority site **is** a ranking and citation system: 176 pages against ~10, every service crossed with every town, every fact marked up so machines can read it. The depth is the product, not the design." },
      ],
    },
    {
      id: "the-matrix",
      h2: "Why the service-by-town matrix is the engine",
      navLabel: "The service x town matrix",
      blocks: [
        { kind: "p", text: "The reason an HVAC site reaches 176 pages and a brochure stalls at ten is the **matrix**: every service multiplied by every town. A homeowner in one suburb does not search the same way as a homeowner two towns over." },
        { kind: "p", text: "One types AC repair plus their town, the next types furnace replacement plus theirs, the next types heat pump installation plus a third. Each is a separate query, and each needs its own page to win it. The brochure has one services page and one location, so it matches one cell of the grid and concedes the rest." },
        { kind: "chart", chart: "matrix" },
        { kind: "p", text: "Read the grid as surface area. Down one axis you list the services: AC install, AC repair, furnace install, furnace repair, heat pump conversion, ductwork, mini-split, IAQ, emergency service, maintenance." },
        { kind: "p", text: "Across the other axis you list the towns you actually work. Every filled cell is a page pointed at a real search a brochure cannot reach." },
        { kind: "p", text: "The deeper site does not out-rank you by writing better copy on ten pages. It is matching searches your ten pages were never built to match." },
        { kind: "p", text: "The matrix is also where most cheap sites cheat, and where Google catches them. A page per town that swaps the city name into the same paragraph is a doorway page, and the search engine has spent years learning to ignore it." },
        { kind: "p", text: "The matrix only works when each cell carries something true and specific to the work in that town. We hold that line below. For the underlying math of why this many low-volume queries adds up to the whole market, see [why a brochure cant win](/guides/why-a-brochure-cant-win)." },
        { kind: "takeaway", text: "The matrix is services times towns. Each filled cell is one page aimed at one real search. A brochure fills one cell and loses the rest of the grid by default." },
      ],
    },
    {
      id: "buyer-tools",
      h2: "The HVAC pages that catch a buyer mid-decision",
      navLabel: "Sizing, cost, repair-vs-replace",
      blocks: [
        { kind: "p", text: "Homeowners do not start by searching for a company. They start with a problem and a question, and they spend weeks researching before anyone signs." },
        { kind: "p", text: "The pages that catch them are the ones that answer those questions better than anyone else: an interactive **AC and furnace sizing tool**, a straight answer on cost, a real **repair-versus-replace** breakdown, a glossary that decodes the jargon they keep hitting. A brochure has none of these, so the researcher lands on the contractor who built them and shortlists that name instead." },
        { kind: "p", text: "Start with sizing, because it is the first thing a homeowner gets wrong. An undersized system runs constantly and never catches up; an oversized one short-cycles, wastes money, and leaves the house humid." },
        { kind: "p", text: "A sizing tool walks them through square footage, climate zone, insulation, and window load to a defensible tonnage and BTU estimate. It is not a quote. It is the page that proves you understand the work, and the page an AI engine can quote when someone asks what size AC a 2,000-square-foot house needs." },
        { kind: "definition", term: "Manual J load calculation", def: "The industry-standard method for sizing a heating and cooling system to a specific home, accounting for square footage, climate, insulation, windows, and air leakage. A real install is sized by Manual J, not by a rule of thumb. A sizing tool gives a homeowner the ballpark; the Manual J gives the contractor the spec." },
        { kind: "p", text: "Then answer the cost question out loud, because it is the most-typed HVAC query there is. The honest move is a range, not a single number, because price swings on tonnage, SEER rating, ductwork condition, and your region." },
        { kind: "p", text: "A homeowner who gets a clear range trusts you; a homeowner who gets a wall of contact forms bounces to the next result. Below is the kind of range a real cost page carries, with the caveat that every figure is illustrative and varies by market, equipment, and home." },
        {
          kind: "priceRange",
          title: "What a new AC or HVAC system costs (illustrative ranges)",
          rows: [
            { label: "Central AC replacement (condenser + coil)", range: "$4,500 - $9,500", detail: "Swings on tonnage and SEER2 rating" },
            { label: "Full system: AC + furnace", range: "$7,000 - $16,000", detail: "Higher with ductwork or zoning" },
            { label: "Heat pump conversion", range: "$6,000 - $18,000", detail: "Varies with cold-climate rating and incentives" },
            { label: "Furnace replacement only", range: "$3,500 - $8,500", detail: "Gas vs. electric, AFUE rating" },
            { label: "Ductless mini-split (per zone)", range: "$3,000 - $6,000", detail: "Multi-zone runs higher" },
          ],
          note: "Illustrative ranges for orientation, not a quote. Actual price depends on home size, equipment efficiency, ductwork condition, regional labor, and current rebates. A real estimate follows a Manual J load calculation and an in-home inspection.",
        },
        { kind: "p", text: "Repair-versus-replace is the decision page that converts. Homeowners staring at a $1,200 repair on a 14-year-old unit want a framework, not a sales pitch." },
        { kind: "p", text: "The honest one is simple and you can publish it: multiply the repair cost by the unit's age; if the product clears roughly $5,000, replacement usually wins. Pair that with the failures that force a replacement, a failed compressor, a cracked heat exchanger, R-22 refrigerant on an old system, and you have a page that earns trust by helping the homeowner decide, including the times the answer is repair." },
        { kind: "list", items: [
          "The $5,000 rule: repair cost x equipment age. Over ~$5,000 and replacement usually wins.",
          "Age past 10-15 years: efficiency has already fallen behind a new SEER2 unit, so even a cheap repair keeps an expensive-to-run system alive.",
          "Refrigerant: a system still on phased-out R-22 gets costly to recharge; that often tips an otherwise-fixable unit toward replacement.",
          "Catastrophic parts: a failed compressor or a cracked heat exchanger is replacement territory, not a repair.",
          "Repeat calls: a third service call in two years is the system telling you it is done.",
        ] },
      ],
    },
    {
      id: "glossary-and-trust",
      h2: "SEER ratings, maintenance plans, and financing: the pages that build trust",
      navLabel: "Glossary, plans, financing",
      blocks: [
        { kind: "p", text: "Homeowners hit a wall of jargon the moment they start researching HVAC, and the contractor who decodes it wins the trust. SEER2, AFUE, HSPF, tonnage, variable-speed, two-stage: each is a query someone is typing right now, and each is a page or a glossary entry an AI engine can quote." },
        { kind: "p", text: "The brochure assumes the homeowner already knows the terms. The authority site teaches them, and the one who teaches is the one who gets the call." },
        { kind: "definition", term: "SEER2 rating", def: "Seasonal Energy Efficiency Ratio 2, the current federal standard for measuring cooling efficiency. Higher is more efficient and cheaper to run. New systems start around 14-15 SEER2 and climb past 20 for premium variable-speed units. A homeowner trading up from an old 10 SEER system can cut cooling cost meaningfully, which is exactly the kind of fact a SEER glossary page is built to answer." },
        { kind: "definition", term: "AFUE rating", def: "Annual Fuel Utilization Efficiency, the heating equivalent of SEER for furnaces. An 80% AFUE furnace turns 80 cents of every fuel dollar into heat; a 95%+ condensing furnace wastes almost nothing. The gap between the two is the homeowner's monthly gas bill, which is why the furnace cost page and the AFUE glossary entry belong together." },
        { kind: "p", text: "Maintenance plans are the page that turns a one-time install into a recurring relationship, and a recurring relationship into reviews and referrals. A membership page that lays out what a plan includes, two tune-ups a year, priority scheduling, a discount on repairs, a longer equipment life, answers a real search and books recurring revenue at the same time." },
        { kind: "p", text: "It also feeds the off-page engine: a homeowner on a maintenance plan is the homeowner who leaves the five-star review that wins the map pack. The site catches them; the relationship keeps them." },
        { kind: "p", text: "Financing is the page that removes the last objection. A $10,000 system is a hard yes; **$130 a month** is an easy one." },
        { kind: "p", text: "A financing page that explains the options, monthly terms, promotional periods, what a soft credit check does and does not do, converts the homeowner who wanted to replace but stalled on the lump sum. It is also a high-intent query in its own right, HVAC financing plus a town, and the brochure has no page for it. Keep the claims clean: state the terms honestly, never promise approval, and follow your lender's disclosure rules." },
        { kind: "takeaway", text: "The glossary, the maintenance page, and the financing page each catch a buyer at a different point in the decision: confusion, commitment, and cash. A brochure has none of the three, so it loses all three buyers silently." },
      ],
    },
    {
      id: "brochure-vs-system",
      h2: "Brochure versus authority site, side by side",
      navLabel: "Brochure vs. system",
      blocks: [
        { kind: "p", text: "The cleanest way to see the gap is to put the two next to each other. The page count is measured: ten on a typical brochure against 176 on our live reference build, more than fifteen times the surface area." },
        { kind: "p", text: "The rest follow from depth. A site with a page for each service in each town has a wide query surface; a brochure has a narrow one. A site that marks up its facts gets read by machines; a brochure does not." },
        {
          kind: "comparison",
          rows: [
            { label: "Pages Google can rank", brochure: "10", system: "176", flag: "MEASURED" },
            { label: "Service x town coverage", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Sizing / cost / repair pages", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Query surface", brochure: "Narrow", system: "Wide", flag: "MEASURED" },
            { label: "LocalBusiness schema", brochure: "No", system: "Yes", flag: "MODELED" },
            { label: "AI-answer legibility", brochure: "No", system: "Yes", flag: "MEASURED" },
          ],
        },
        { kind: "p", text: "There is a measured reason most brochures are missing the bottom rows, not just the top ones. Across a broad audit, **94.8% of contractor sites fail WCAG accessibility**, **roughly 52% fail Core Web Vitals**, **around 27% have no dedicated site at all**, and the overwhelming majority ship **no LocalBusiness schema** (modeled, but the direction is not in doubt)." },
        { kind: "p", text: "The fundamentals are not rare to do well. They are rare to do at all, which is exactly why doing them is an advantage." },
        { kind: "debunk", myth: "A better-looking HVAC site will out-rank a deeper one.", reality: "Design does not decide the considered search; surface area and structure do.", why: "Ten polished pages still match only ten kinds of query. The deeper site is being returned for hundreds of service-and-town searches your ten pages were never built to reach. You cannot write your way past a page that does not exist." },
        { kind: "p", text: "One honest guardrail on the page count: 176 only means something if the pages are real. Depth is the floor that makes ranking possible, not a guarantee of a #1 spot, and no one honest will sell you the guarantee." },
        { kind: "p", text: "What depth gives you is the only thing that **can** win the search a brochure has no page for. See [the gap most sites have](/guides/the-gap-most-sites-have) for what lives under the surface of those pages." },
      ],
    },
    {
      id: "real-pages-only",
      h2: "Every town page has to earn its place",
      navLabel: "Real pages only",
      blocks: [
        { kind: "p", text: "The matrix is powerful and it is also where the temptation to cheat is strongest. The lazy version is a doorway page: one template, the city name swapped in, published a hundred times." },
        { kind: "p", text: "It looks like coverage. Google reads it as spam, because it is, and the whole matrix collapses with it. An authority HVAC site only works when every cell of the grid carries something true and specific to the work in that town." },
        { kind: "antiDoorway" },
        { kind: "p", text: "For HVAC the specifics are not hard to find, because the work genuinely differs by place. Climate zone changes the sizing math and tips heat pumps in or out." },
        { kind: "p", text: "Local utility rebates and the federal incentives differ by jurisdiction. Older housing stock means more ductwork and retrofit; newer subdivisions mean clean installs." },
        { kind: "p", text: "Permit rules and inspection requirements vary by municipality. A real town page reflects the work you actually do there: the systems you install most, the jobs you have completed, the inspectors you pull permits from. The delete-the-city-name test is the gate: if removing the town name leaves a page that could be about anywhere, the page is not real yet." },
        { kind: "p", text: "Hold that line and the depth compounds instead of decaying. Each real page earns a little trust, the trust lifts the next page, and the matrix becomes an asset that grows every month rather than a liability waiting for an algorithm update." },
        { kind: "p", text: "Build it on doorway pages and the opposite happens: one update and the whole grid drops at once. For the full mechanism of why depth done right compounds and rented traffic does not, see [organic vs paid](/guides/organic-vs-paid), then run your own site through the [audit](/audit) and count how many of your pages would survive the delete-the-city-name test." },
        { kind: "takeaway", label: "The honest version", text: "176 pages is a category change, not a tweak, but only if every page is real. We will not promise a #1 ranking, because no one honest can. We will tell you the matrix is the only structure that **can** win the considered HVAC search, and a doorway-page version of it is worse than ten honest pages. Audit both claims with any AI." },
      ],
    },
  ],
};
