import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "what-it-ships",
      h2: "What does an authority kitchen & bath remodel site actually ship?",
      navLabel: "What it ships",
      speakable: true,
      blocks: [
        { kind: "p", text: "A remodel buyer does not search for your company. She searches for the decision she is in the middle of: how much a kitchen remodel costs in her town, whether quartz beats granite, what a bathroom gut takes from demolition to final walkthrough, what a transitional kitchen even looks like." },
        { kind: "p", text: "A brochure has none of those pages. It has a homepage, a services list, an about page, a gallery, a contact form." },
        { kind: "p", text: "Roughly **ten pages**, each describing the business in general terms, none of them answering the question a buyer types. Our live reference build ships **159 pages**, and every one is pointed at a real search a homeowner makes while deciding." },
        { kind: "p", text: "The difference is not polish. A brochure can be beautiful and still lose, because ten pages can match only ten kinds of search." },
        { kind: "p", text: "Real remodel demand is hundreds of distinct queries wide: every service crossed with every town, plus the cost questions, the material comparisons, the timeline questions, and the design-style questions buyers ask for months before they ever know a name to call. An authority site is built as the answer to each of those, one page per band of demand, so the buyer keeps landing on you no matter which question she opened Google with." },
        {
          kind: "comparison",
          rows: [
            { label: "Pages Google can rank", brochure: "10", system: "159", flag: "MEASURED" },
            { label: "Service x town coverage", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Remodel cost estimator", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Countertop / cabinet comparison", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Design-style gallery", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "What-to-expect timeline", brochure: "No", system: "Yes", flag: "MEASURED" },
          ],
        },
        { kind: "takeaway", text: "A remodel brochure ranks for your **name** and your **home city**. An authority site ranks for the **decision** the buyer is actually making: the cost, the material, the style, the timeline. That is roughly a **fifteenfold** difference in the searches the site can win." },
      ],
    },
    {
      id: "the-matrix",
      h2: "The matrix: every service in every town is its own page",
      navLabel: "The matrix",
      blocks: [
        { kind: "p", text: "Kitchen and bath is a wide trade. Kitchen remodels, bathroom remodels, kitchen cabinet refacing, countertop installation, walk-in shower conversions, master bath suites, small-bath renovations, basement bathrooms, accessible aging-in-place baths." },
        { kind: "p", text: "Each of those is a distinct service, and a buyer searches for it paired with where she lives. A brochure folds all of it into one services page that ranks for none of them. The system multiplies them: every service crossed with every town is its own page, each answering one query better than anyone else." },
        { kind: "chart", chart: "matrix" },
        { kind: "p", text: "This is the engine of the long tail. People do not type your company name, they type what they need and where they are." },
        { kind: "p", text: "**95% of search queries get ten or fewer searches a month**, so individually each service-and-town page looks like nothing. Added together they are the entire market." },
        { kind: "p", text: "The brochure's pages sit at zero because they match no specific search: **96.55% of all web pages get zero traffic from Google**, and a generic services page is exactly one of those pages. The matrix exists to drag every cell of demand off zero." },
        { kind: "p", text: "The hard rule is that each cell must be a real page. A bathroom-remodel page that just swaps one town name for another is a doorway, and Google has spent a decade learning to ignore it." },
        { kind: "p", text: "The page for kitchen remodels in one suburb has to carry a true and specific job from that area: the actual work, the actual constraints, the actual before and after. Cover the grid honestly and you own the considered search across the whole service area. Fake the grid and you earn nothing." },
        { kind: "takeaway", label: "The mechanism", text: "Demand is service **times** town, hundreds of cells wide. A brochure is one services page against the whole grid. The matrix builds the grid, one real page per cell, and that is how a site matches searches a brochure structurally cannot reach." },
      ],
    },
    {
      id: "cost-estimator",
      h2: "How much does a remodel cost: the question every buyer types first",
      navLabel: "The cost question",
      blocks: [
        { kind: "p", text: "The first thing a remodel buyer searches is price. How much does a kitchen remodel cost, how much for a bathroom, how much for quartz countertops, how much to move a wall." },
        { kind: "p", text: "A brochure answers none of it, because pricing makes contractors nervous and they leave it off the site entirely. So the buyer goes to the contractor who answered, reads his cost page, and starts trusting him before she has spoken to anyone. The contractor who hid the number is already losing, silently, to the one who showed it." },
        { kind: "p", text: "An authority site answers the cost question two ways. A written cost page that ranks for the search and frames the real ranges, and an interactive estimator that turns a passive reader into a lead." },
        { kind: "p", text: "The estimator is not a fixed price list, it is a conversion lever: a buyer picks her scope and finishes, learns roughly where she lands, and hands you her contact in exchange. She qualifies herself before you ever pick up the phone." },
        {
          kind: "priceRange",
          title: "Remodel cost bands shown on the estimator + cost pages",
          rows: [
            { label: "Bathroom refresh (cosmetic)", range: "$8k - $18k", detail: "Fixtures, vanity, tile, paint; layout unchanged" },
            { label: "Full bathroom remodel", range: "$18k - $40k", detail: "Gut to studs, new layout, walk-in shower" },
            { label: "Midrange kitchen remodel", range: "$30k - $70k", detail: "New cabinets, counters, appliances, flooring" },
            { label: "Upscale / full kitchen", range: "$70k - $150k+", detail: "Custom cabinetry, structural changes, high-end finishes" },
          ],
          note: "Illustrative ranges for an estimator and cost-page surface, not a fixed quote. Actual figures vary by region, scope, and materials, which is exactly why the estimator collects scope before it shows a number.",
        },
        { kind: "p", text: "The mechanism behind this is the buyer journey. **78% of buyers shortlist three vendors or fewer**, and **95% pick a name that was on their shortlist from day one.** The cost page is how you get on the shortlist before the conversation." },
        { kind: "p", text: "If you are the contractor who answered the price question honestly when nobody else would, you are already the trusted name when she finally calls. The home-improvement research window can run on the order of **~94 days** (illustrative, it varies widely by ticket), and you want to be the page she keeps returning to for all of it." },
      ],
    },
    {
      id: "materials-and-style",
      h2: "Countertops, cabinets, and design style: the decisions the buyer agonizes over",
      navLabel: "Materials & style",
      blocks: [
        { kind: "p", text: "Between the cost question and the call, a remodel buyer makes a hundred small decisions, and she researches every one. Quartz or granite." },
        { kind: "p", text: "Stained wood cabinets or painted shaker. Modern, transitional, or farmhouse." },
        { kind: "p", text: "Each decision is a search, and each search is a page a brochure does not have. An authority site has all of them: a countertop comparison, a cabinet comparison, a design-style gallery organized by the look a buyer is chasing, not by the project you happened to photograph." },
        {
          kind: "comparison",
          leftLabel: "Brochure gallery",
          rightLabel: "Authority gallery",
          rows: [
            { label: "Organized by buyer intent (style, room, material)", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Countertop comparison page (quartz vs granite vs)", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Cabinet comparison (custom vs semi vs reface)", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Style pages (modern, transitional, farmhouse)", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Each photo set tied to a real local job", brochure: "No", system: "Yes", flag: "MEASURED" },
          ],
        },
        { kind: "definition", term: "Comparison page", def: "A page built around a decision the buyer is stuck on (quartz vs granite, refacing vs replacement). It ranks for the comparison query, settles the decision, and positions you as the expert who settled it. A brochure has zero of these; they are pure long-tail surface a deeper site owns by default." },
        { kind: "p", text: "The reason a deeper site wins these is structural, not stylistic. **94.8% of sites fail basic accessibility, roughly 52% fail Core Web Vitals, around 27% have no dedicated site at all, and an estimated 96% ship no LocalBusiness schema.** The field is wide open." },
        { kind: "p", text: "You do not out-rank a comparison page that does not exist. When you publish the quartz-versus-granite page and the modern-kitchen gallery and the competitor publishes neither, the search has exactly one good answer, and it is yours. See [the gap most sites have](/guides/the-gap-most-sites-have) for the full wall of what is missing." },
        { kind: "takeaway", text: "Every decision a remodel buyer agonizes over is a **search** and therefore a **page**. The comparison pages and style galleries are not nice-to-haves; they are the long-tail surface that a brochure cannot reach and a deeper site owns uncontested." },
      ],
    },
    {
      id: "timeline-trust",
      h2: "The what-to-expect timeline: turning a scary process into a signed job",
      navLabel: "The timeline page",
      blocks: [
        { kind: "p", text: "A remodel is invasive and slow, and the buyer knows it. She has heard the horror stories: the kitchen torn up for four months, the contractor who vanished mid-project." },
        { kind: "p", text: "Her real fear is not the price, it is the chaos. A brochure does nothing to answer that fear." },
        { kind: "p", text: "An authority site has a what-to-expect timeline that walks the entire process, demolition through final walkthrough, with realistic durations at each stage, so the buyer can see exactly what she is signing up for. The page that removes the fear is the page that earns the call." },
        {
          kind: "list",
          ordered: true,
          items: [
            "Design + selections: 2 to 6 weeks of layout, materials, and final scope before anything is touched.",
            "Permits + ordering: 2 to 8 weeks; cabinetry and stone are long-lead items that gate the schedule.",
            "Demolition: a few days to gut the space back to a clean working shell.",
            "Rough-in: plumbing, electrical, framing, and the inspections that follow.",
            "Install: cabinets, countertops, tile, fixtures; the longest hands-on stretch.",
            "Punch list + final walkthrough: the details, the clean, and the sign-off.",
          ],
        },
        { kind: "p", text: "The timeline page does what the cost page does, for trust instead of price. It ranks for the search (how long does a kitchen remodel take, what to expect during a bathroom remodel) and it converts, because a buyer who understands the process is a buyer ready to commit." },
        { kind: "p", text: "It is also where you set honest expectations: a full kitchen runs weeks, not days, and the contractor who says so plainly reads as the professional. This is the [organic-over-paid](/guides/organic-vs-paid) advantage in miniature, the page works for free, every day, for every buyer who finds it, long after it is published." },
        { kind: "p", text: "Authority pages like this also compound, because Google rewards accumulated time. **72.9% of the pages ranking in the top ten are three or more years old, and the average #1 result is five years old.** A timeline page published today is not at full strength tomorrow; it earns its position by aging in place while a competitor's brochure has no such page to age at all. The earlier you build the surface, the longer it has to compound." },
        { kind: "chart", chart: "page-age" },
      ],
    },
    {
      id: "anti-doorway",
      h2: "Why depth only wins when every page is real",
      navLabel: "Real pages only",
      blocks: [
        { kind: "p", text: "The danger in a 159-page site is the temptation to fake the depth. Generate a bathroom-remodel page for every town by swapping the city name into one paragraph, and the count looks impressive." },
        { kind: "p", text: "It is also worthless. Google has spent years learning to detect exactly that pattern, and a thin town page earns nothing or, worse, drags down the pages around it. Depth wins only when every page is genuinely about the work it claims." },
        { kind: "antiDoorway" },
        { kind: "p", text: "The honest guardrails are two. First, every page must carry something true and specific to its claim: a real local kitchen job behind the kitchen-in-that-town page, a real bathroom behind the bathroom page, an actual cost reasoned through on the cost page." },
        { kind: "p", text: "Second, depth is the floor, not a guaranteed ceiling. No one honest sells you a guaranteed #1, and a deeper site does not promise the top spot. What it gives you is the only thing that **can** win the considered search: a real page that matches the query when a brochure has none." },
        { kind: "p", text: "That is the whole mechanism. A remodel buyer spends weeks deciding, searching the cost, the materials, the style, and the timeline." },
        { kind: "p", text: "A brochure is invisible for all of it. An authority site is the page she keeps landing on, the name that earned its place on the shortlist before you ever spoke." },
        { kind: "p", text: "Build the matrix for real and you are the answer Google returns. Next, see [why a brochure can't win](/guides/why-a-brochure-cant-win), or run your own site through the [audit](/audit) and count how many of your pages match a real remodel search." },
      ],
    },
  ],
};
