import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "what-five-million-is-built-on",
      h2: "What does a $5M+ contractor actually run on?",
      navLabel: "The infrastructure",
      speakable: true,
      blocks: [
        { kind: "p", text: "A five-million-dollar contractor does not work harder than a one-million-dollar contractor. He works on top of a layer the smaller business does not have." },
        { kind: "p", text: "Underneath the trucks and the crews sits an infrastructure: a system that catches every lead, answers it in seconds, follows it until it closes, and tracks it through to a paid invoice without the owner standing in the middle of any of it. The work is the same work. The machine around the work is what changed." },
        { kind: "p", text: "This is the part the ceiling chapter pointed at and did not finish. Breaking past one or two million removes the owner as the bottleneck, but removing a bottleneck is not the same as building what replaces it." },
        { kind: "p", text: "What replaces the owner is plumbing: a CRM that holds every lead, a speed-to-lead rule that touches each one inside a minute, a missed-call text-back that refuses to let a ring go to a competitor, a pipeline that shows every job by stage, and a fulfillment side, estimating, scheduling, crews, that can absorb the volume the demand engine produces. Demand without that plumbing does not become revenue. It becomes leaks." },
        { kind: "p", text: "And every piece of it splits into two categories that decide whether the business is durable or borrowed: the assets you own and the positions you rent. The owner builds on what he owns." },
        { kind: "p", text: "The renter builds on what a platform can revoke. That single distinction is the difference between a company worth selling and a company that evaporates the day a map pin gets suspended. We start with the plumbing, then we draw that line." },
        { kind: "takeaway", text: "A $5M+ contractor runs on **infrastructure, not effort**: a CRM, speed-to-lead, missed-call text-back, and a pipeline that convert demand into jobs without the owner inside each step, plus a fulfillment side that can take the volume. The deeper rule underneath it: build on what you **own**, not on what a platform can **revoke**." },
      ],
    },
    {
      id: "speed-to-lead",
      h2: "Speed-to-lead is the lever no contractor pulls",
      navLabel: "Speed-to-lead",
      blocks: [
        { kind: "p", text: "A lead is perishable. The moment a homeowner submits a form or dials a number, a timer starts, and it runs against you." },
        { kind: "p", text: "They did not call one contractor. They called several, and the first real human voice that reaches them shapes the entire decision." },
        { kind: "p", text: "Reach them in the first minute and you are the company they are talking to. Reach them in an hour and you are the company calling back about a job they already gave to someone else." },
        { kind: "p", text: "Speed is not customer service. Speed is the conversion lever, and it is the one almost no contractor actually pulls." },
        { kind: "p", text: "The reason is structural, not lazy. The owner who is the machine cannot answer in sixty seconds, because in any given sixty seconds he is on a roof, under a sink, or in front of another customer." },
        { kind: "p", text: "Manual speed-to-lead is impossible for a busy operator by definition: the busier the business, the slower the response, which is exactly backwards from what wins. So the answer is not discipline. The answer is a system that does the first touch whether the owner is reachable or not." },
        { kind: "list", items: [
          "Every inbound lead, web form or phone, lands in one CRM the instant it arrives, never an inbox someone checks twice a day.",
          "An automated first touch fires inside a minute: a text and an email that confirm a real company received the request.",
          "The job is assigned to a person and a clock starts, so a lead cannot sit untouched and unnoticed.",
          "A follow-up sequence runs on its own across days, because most jobs do not close on the first contact, they close on the fifth.",
        ] },
        { kind: "p", text: "Notice what the system does to the owner's role. It does not ask him to be faster." },
        { kind: "p", text: "It removes him from the critical first minute entirely, so the response time of the business stops being a function of how busy one human is. That is the whole move. The lead gets caught at machine speed, and the owner gets pulled in only when there is a real conversation to have." },
        { kind: "takeaway", text: "A lead is **perishable**, and the first real contact usually wins the job. Manual speed-to-lead is impossible for a busy operator, the busier he is, the slower he answers, so the fix is a **system** that does the first touch in under a minute, not a person trying harder." },
      ],
    },
    {
      id: "missed-call-text-back",
      h2: "The missed call is a lead you already paid for",
      navLabel: "Missed-call text-back",
      blocks: [
        { kind: "p", text: "Consider the single most expensive event in a contractor's day: the phone rings and no one picks up. The crew is on a ladder, the office is with a walk-in, the call comes in at 6 p.m." },
        { kind: "p", text: "The caller does not leave a voicemail. They hang up and dial the next name on the list. That call was a lead you already paid for, marketing spent the money to make the phone ring, and it walked out the door in the four seconds it took to decide nobody was answering." },
        { kind: "p", text: "Missed-call text-back closes that exact gap, and it is the highest-leverage piece of automation a contractor can install. The mechanism is simple and that is the point." },
        { kind: "p", text: "The instant a call goes unanswered, an automatic text goes back to the number that called: a real message, from the business, saying we saw you call and we will help, what do you need. The caller who was about to dial a competitor is now in a text conversation with you instead. The lead that was leaving is caught before it reaches the door." },
        { kind: "p", text: "The leverage is in the cost structure. You already spent the money to generate the call." },
        { kind: "p", text: "The text-back recovers leads that were already paid for and already lost, which means its return is not measured against new spend, it is measured against pure waste eliminated. Every recovered call is margin that would otherwise have funded a competitor's job. This is why it sits at the top of the list: nothing else turns money you have already spent back into revenue at the same rate." },
        { kind: "takeaway", text: "A missed, unanswered call is a lead you **already paid for**, walking to a competitor in seconds. Missed-call text-back fires an automatic reply the instant the call drops, turning the caller into a text conversation with you. It recovers spend you have already lost, which is why it is the **highest-leverage** automation a contractor can run." },
      ],
    },
    {
      id: "crm-and-pipeline",
      h2: "The CRM is the floor every other system stands on",
      navLabel: "CRM and pipeline",
      blocks: [
        { kind: "p", text: "Speed-to-lead and text-back are reflexes. The CRM is the nervous system that makes the reflexes possible, and without it neither one can exist." },
        { kind: "p", text: "A lead in a notebook cannot be auto-texted. A lead in someone's inbox cannot trigger a follow-up sequence." },
        { kind: "p", text: "A lead in the owner's memory cannot be tracked, forecast, or handed to a salesperson. Every automation in this chapter assumes one thing: that every lead lives in one place, in one record, the moment it arrives." },
        { kind: "p", text: "The CRM is that place. It is the floor everything else stands on." },
        { kind: "definition", term: "Pipeline", def: "The CRM view that shows every active job as a card on a board, sorted by stage: new lead, contacted, estimate sent, won, scheduled, complete. It turns the business from a memory the owner carries into a board anyone can read, so no job stalls in silence and revenue can be forecast instead of guessed." },
        { kind: "p", text: "The pipeline is what turns the CRM from a list into management. A flat list of contacts tells you who exists." },
        { kind: "p", text: "A pipeline tells you where every job is, what is stuck, and what is about to close, which is the difference between running a business and reacting to one. An estimate sent four days ago with no follow-up is visible as a card sitting too long in a column, not an opportunity quietly dying because the one person tracking it got busy. The pipeline makes the leaks visible, and a leak you can see is a leak you can fix." },
        { kind: "p", text: "There is a second, larger reason the CRM is non-negotiable, and it is about who owns the business. Leads and customer history in one owned system are a durable asset: a list you can market to again, a history that makes the next sale easier, a record that has real value the day you sell the company." },
        { kind: "p", text: "Leads scattered across a personal phone, an email account, and the owner's head are not an asset at all. They are a liability that walks out the door the day that person does. The CRM is where the customer relationship gets owned instead of borrowed, which is the thread that runs through the rest of this chapter." },
        { kind: "takeaway", text: "The CRM is the **floor** every other system stands on: no shared record, no automation, no forecast. The pipeline turns it from a list into management by making stalled jobs **visible**. And it is where customer relationships become an **owned asset** instead of data scattered across one person's phone and memory." },
      ],
    },
    {
      id: "fulfillment-adds-crews",
      h2: "The systems that let you add a crew without breaking",
      navLabel: "Adding crews",
      blocks: [
        { kind: "p", text: "A demand engine that the fulfillment side cannot absorb is not growth, it is a fire. Catch more leads than you can estimate and you create a backlog of angry people." },
        { kind: "p", text: "Win more jobs than you can schedule and you blow timelines and burn the reviews that feed the engine. The lead side and the delivery side have to scale together, and the delivery side scales the same way the lead side does: by turning what lives in the owner's head into a system anyone can run. You cannot add a crew if the only person who knows how to estimate, schedule, and run a job is the founder." },
        { kind: "p", text: "Estimating is the first thing that has to leave the founder's head. At a million dollars the owner walks every job and prices it by feel, and that feel is the bottleneck: the business can only sell as fast as one person can drive to estimates." },
        { kind: "p", text: "The five-million version is a documented, repeatable estimating process, standard pricing, standard scopes, standard materials, that a trained estimator can execute to the same standard. The moment the price stops depending on one person's instinct, the company can sell faster than that one person can drive." },
        { kind: "list", items: [
          "Estimating: documented pricing, scopes, and materials so a trained estimator quotes to the same standard the owner would, without the owner present.",
          "Scheduling: a central calendar tied to the pipeline, so a won job becomes a scheduled job on its own and two crews are never double-booked.",
          "Fulfillment: a standard job process, crew checklists, quality checks, customer updates, so the experience is consistent no matter which crew shows up.",
          "Capacity: hiring and onboarding that runs to a playbook, so adding a crew is a repeatable step, not a crisis the owner manages by hand each time.",
        ] },
        { kind: "p", text: "The pattern is identical across all four, and it is the same pattern as the lead side. Take the thing the owner does by instinct, document it into a process, and hand the process to a person who is not the owner." },
        { kind: "p", text: "A crew is not just labor you add. It is load placed on the systems around the crew, and if those systems do not exist, the crew breaks them and the owner gets pulled back into the middle of the work he was trying to climb out of." },
        { kind: "p", text: "Build the system first. Then the crew is something you add, not something you survive." },
        { kind: "takeaway", text: "The delivery side has to scale with the demand side or growth becomes a fire. **Estimating, scheduling, fulfillment, and capacity** each have to leave the founder's head and become a documented process. A crew is **load on the systems around it**, build the systems first, and adding crews stops being a crisis." },
      ],
    },
    {
      id: "owned-vs-rented",
      h2: "Owned vs. rented: a map pin is a suspension risk",
      navLabel: "Owned vs. rented",
      blocks: [
        { kind: "p", text: "Everything in this chapter splits along one line, and it is the line that decides whether the business is durable. Some of your infrastructure you own." },
        { kind: "p", text: "Some of it you rent. The owned assets cannot be taken from you. The rented positions can be revoked by a platform on a Tuesday with no warning and no appeal, and the contractor who built his lead flow on rented ground discovers this at the worst possible moment, when the leads stop and there is no one to call." },
        { kind: "p", text: "The map pin is the clearest example, so name it plainly. A Google Business Profile is rented." },
        { kind: "p", text: "It is a tremendous lead source, the pack catches the nearby and the urgent, and you should absolutely run it, but the listing sits on Google's platform under Google's rules, and a suspension, for a reason as small as a service-area edit or a category change, takes the whole thing offline at once. Contractors lose their primary lead source to a suspension regularly, and recovery is a slow appeal to a company with no phone number." },
        { kind: "p", text: "A pin is a position you hold at someone else's pleasure. It is not an asset you own." },
        { kind: "comparison", leftLabel: "Rented", rightLabel: "Owned", rows: [
          { label: "The map pin", brochure: "Suspendable", system: "—", flag: "ILLUSTRATIVE" },
          { label: "Your website + domain", brochure: "—", system: "Yours", flag: "ILLUSTRATIVE" },
          { label: "Lead list + CRM", brochure: "—", system: "Yours", flag: "ILLUSTRATIVE" },
          { label: "Paid ad position", brochure: "Stops when spend stops", system: "—", flag: "MEASURED" },
          { label: "Ranked organic pages", brochure: "—", system: "Compounding", flag: "MEASURED" },
          { label: "Can be revoked", brochure: "Yes", system: "No", flag: "ILLUSTRATIVE" },
        ] },
        { kind: "p", text: "The owned assets are a different species. Your website and the domain it runs on are yours, no platform can suspend your own site." },
        { kind: "p", text: "The ranked organic pages on that site are an accumulating position that compounds, and authority is accumulated time: across the top of competitive results, 72.9% of the pages are three or more years old and the average number-one page is roughly five years old, which means the position you build is one a new competitor cannot simply buy. Your CRM and your lead list are yours, a real asset the day you sell the company. None of these can be revoked, because none of them sit on someone else's platform." },
        { kind: "p", text: "So the rule is not own instead of rent. It is build on what you own, and use what you rent without depending on it." },
        { kind: "p", text: "Run the pin, run the ads, take the proximity and the day-one speed they buy, but make the durable center of the business the website you own and the relationships you control. The contractor who treats a map pin as his foundation is one suspension from zero." },
        { kind: "p", text: "The contractor who treats it as one rented surface on top of an owned asset is not. To see how the owned engine outscales the rented pin, read [organic versus the map pack](/playbook/organic-vs-the-map-pack), or run your own site through the [audit](/audit) and see how much of your lead flow is borrowed." },
        { kind: "takeaway", text: "Build on what you **own**, use what you **rent** without depending on it. A map pin and a paid position are rented, revocable on a platform's terms with no appeal. Your **website, domain, ranked pages, and lead list** are owned and cannot be taken. The contractor whose foundation is a rented pin is one suspension from zero." },
      ],
    },
  ],
};
