import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "engine-or-anchor",
      h2: "Is your website an engine or an anchor?",
      navLabel: "Engine or anchor",
      speakable: true,
      blocks: [
        { kind: "p", text: "Your website is one of two things. It is the engine that converts demand into booked jobs, or it is the anchor that caps everything you bolt onto it." },
        { kind: "p", text: "There is no neutral middle. Every dollar you spend on ads, every review you earn, every link you build flows through the site before it reaches a buyer." },
        { kind: "p", text: "If the site is a 2 out of 10, that is the ceiling on the whole machine. You can pour fuel into a leaking tank for years and call it a budget problem." },
        { kind: "p", text: "It is not. It is an infrastructure problem, and the site is the infrastructure." },
        { kind: "p", text: "The standard contractor site is a brochure: roughly ten pages built to describe the business. It ranks for the company name and the block the office sits on, and it loses every other search to whoever built the page for it." },
        { kind: "p", text: "That is not a small gap. It is the difference between a site that can answer the hundreds of questions a buyer actually types and a site that can answer almost none of them." },
        { kind: "p", text: "A brochure is a business card with a domain attached. It does not rank, it does not compound, and it does not absorb the money you spend everywhere else." },
        { kind: "p", text: "We covered where the high-ticket jobs come from in [where high-ticket jobs come from](/playbook/where-high-ticket-jobs-come-from): the considered buyer researches, shortlists, and picks the authority. This chapter is about the thing that buyer lands on." },
        { kind: "p", text: "Get the asset right and every other lever multiplies. Get it wrong and every other lever is capped at the level of a brochure." },
        { kind: "takeaway", text: "The site is the engine or the anchor, never neutral. A **2/10 brochure** caps every dollar you spend on top of it. Fix the asset first, because everything else flows through it." },
      ],
    },
    {
      id: "why-a-brochure-caps-everything",
      h2: "Why a 2/10 site caps everything above it",
      navLabel: "The ceiling",
      blocks: [
        { kind: "p", text: "The brochure is not bad because it is ugly. It is bad because it is structurally incapable of ranking for the demand that exists." },
        { kind: "p", text: "**95%** of search queries get ten or fewer searches a month (MEASURED), which means the demand is not in a handful of fat keywords, it is spread across thousands of specific questions. A ten-page site has no page for almost any of them." },
        { kind: "p", text: "It cannot win what it does not address. And **96.55%** of all web pages get zero Google traffic (MEASURED): a page that does not deserve to rank simply does not, and a brochure is mostly pages that do not deserve to rank." },
        { kind: "p", text: "It gets worse below the surface. The field is not failing at the hard things, it is failing at the floor." },
        { kind: "p", text: "Across the broad web, **94.8%** of homepages fail WCAG accessibility, roughly **52%** of pages fail Core Web Vitals, and an estimated **96%** ship no LocalBusiness schema (the first two MEASURED, the schema figure MODELED). A search engine cannot rank what it cannot read, cannot trust what it cannot crawl quickly, and cannot place what carries no structured facts. The brochure fails all three and then the owner blames the ad budget." },
        { kind: "comparison", leftLabel: "Brochure", rightLabel: "Authority system", rows: [
          { label: "Pages Google can rank", brochure: "10", system: "147", flag: "MEASURED" },
          { label: "Query surface", brochure: "Narrow", system: "Wide", flag: "MEASURED" },
          { label: "LocalBusiness schema", brochure: "No", system: "Yes", flag: "MEASURED" },
          { label: "AI-answer legibility", brochure: "No", system: "Yes", flag: "MEASURED" },
        ] },
        { kind: "p", text: "Our live reference build ships **147** pages against the brochure's **10**, roughly fifteen times the surface area Google can rank (147 is MEASURED for the live build; state the multiple conservatively). That is not padding." },
        { kind: "p", text: "Every page exists because a real job and a real query justify it. The brochure caps you because it has nowhere to put the answers." },
        { kind: "p", text: "The system wins because it has a page for each one. We take the structural argument apart in [why a brochure can't win](/guides/why-a-brochure-cant-win) and [the gap most sites have](/guides/the-gap-most-sites-have)." },
        { kind: "takeaway", text: "Demand is **long-tail**: 95% of queries get under 10 searches a month, and 96.55% of pages get zero traffic. A brochure has no page for almost any of it, so it caps you at the few searches it can address." },
      ],
    },
    {
      id: "what-an-authority-site-is",
      h2: "What an authority site actually is",
      navLabel: "The five pillars",
      blocks: [
        { kind: "p", text: "An authority site is not a prettier brochure. It is a ranking system, and a system has parts that work together." },
        { kind: "p", text: "There are five, and a site that skips any one of them is a site that leaks. Deep silos so there is a page for every job and every place." },
        { kind: "p", text: "Structured schema so a machine can read every fact. Speed so the page loads before the buyer leaves." },
        { kind: "p", text: "E-E-A-T so the trust signals are on the page, not implied. And AI-readiness so the answer engines can cite you." },
        { kind: "p", text: "Each pillar is load-bearing. Together they are the asset." },
        { kind: "definition", term: "Deep silos", def: "Service pages and location pages organized into tight topical clusters, internally linked, so the site covers a trade across a region one specific page at a time, the service-by-location matrix the brochure never builds." },
        { kind: "chart", chart: "matrix" },
        { kind: "list", ordered: true, items: [
          "Deep silos: a dedicated page for every service and every city, meshed into clusters so the demand is covered specifically, not gestured at on one thin services page.",
          "Structured schema: LocalBusiness, service, and FAQ schema on every page, so the engine reads your hours, ratings, and facts as data instead of guessing at them.",
          "Speed: Core Web Vitals that pass, because a page that loads slowly loses the buyer and the ranking before either is earned.",
          "E-E-A-T: experience, expertise, authoritativeness, and trust shown on the page, real projects, real credentials, real answers, the signals Google's quality systems reward.",
          "AI-readiness: answer-first content and clean machine-readable markup so AI answer engines can extract and cite you, because that is now its own surface.",
        ] },
        { kind: "p", text: "That last pillar is not optional anymore. AI Overviews cut clicks to the top result by about **34.5%** in April 2025 and roughly **58%** by December 2025, and around **60%** of searches now end without a click (MEASURED)." },
        { kind: "p", text: "A page that gets cited in the AI answer earns about **35%** more organic clicks (MEASURED), and here is the part the brochure cannot survive: **88%** of AI-cited URLs do not rank in the top ten (MEASURED). AI citation is its own surface with its own rules." },
        { kind: "p", text: "You structure for it or you are invisible to it. We go deeper in [winning the AI answer](/guides/winning-the-ai-answer) and lay out the full build in [the anatomy of an enterprise website](/guides/enterprise-website-anatomy)." },
        { kind: "takeaway", text: "An authority site is five load-bearing pillars: **deep silos, schema, speed, E-E-A-T, AI-readiness**. Skip one and the system leaks. The brochure has none of them, which is why it is a 2/10." },
      ],
    },
    {
      id: "the-asset-compounds",
      h2: "Why the asset appreciates and rent does not",
      navLabel: "The asset compounds",
      blocks: [
        { kind: "p", text: "Here is the difference that decides the next five years. Paid traffic is rent: it works while you pay and stops the day you stop." },
        { kind: "p", text: "The authority site is equity: built once, owned, and it compounds. The first page you rank teaches the engine your site is a credible answer for this trade in this region." },
        { kind: "p", text: "The next page inherits that credibility and climbs faster. The tenth page lands half-trusted on day one." },
        { kind: "p", text: "Every win lowers the cost of the next win. Ads have no flywheel, the thousandth click costs exactly what the first one did." },
        { kind: "chart", chart: "compounding" },
        { kind: "p", text: "The shape above is the whole argument. Paid is a flat line, it resets to zero the month you stop feeding it." },
        { kind: "p", text: "Organic climbs and keeps climbing after the spend flattens, because rankings are durable: **72.9%** of the pages in the top ten are three or more years old, and the average #1 page is five years old (MEASURED). Authority is accumulated time." },
        { kind: "p", text: "A new page takes time to mature, that is honest. The flip side is the moat: once your page is in there, the same five-year wall you climbed is now staring at the competitor who launches next year." },
        { kind: "p", text: "The cost follows the trust. Mature organic cost per lead runs around **$30**, against roughly **$228** for PPC and **$162** for Local Services Ads (MEASURED ranges), and the organic line crosses below paid around month six (ILLUSTRATIVE, the exact month varies by market and starting authority)." },
        { kind: "p", text: "This is not an argument against ads. Run organic and paid together and total clicks lift about **50%** and conversions about **27%** over either alone (MEASURED)." },
        { kind: "p", text: "Ads earn the emergency and buy day-one speed. The site keeps the value after the spend ends. We split the channel math fully in [organic vs. ads](/playbook/organic-vs-ads) and [your site is an asset](/guides/your-site-is-an-asset)." },
        { kind: "takeaway", label: "The honest version", text: "The site is the only marketing line that **appreciates**: it compounds page over page and durability defends it for years. Mature organic CPL ~$30 vs ~$228 PPC; the curve crosses below paid around month six (illustrative). Promise the floor, project the ceiling." },
      ],
    },
    {
      id: "link-absorption",
      h2: "Why a deep site absorbs an off-page budget and a thin one over-optimizes",
      navLabel: "Link absorption",
      blocks: [
        { kind: "p", text: "This is the pillar most people never hear, and it is the reason the site has to come first. Off-page work, the links and citations and authority signals that move a site up, has a capacity limit, and the limit is set by the depth of the site receiving it." },
        { kind: "p", text: "A deep authority site has a wide, natural surface to distribute that authority across: dozens of service and location pages, each a legitimate destination for a relevant link. The signals spread out and look exactly like what they are, a credible business earning credible mentions." },
        { kind: "p", text: "A thin brochure has nowhere to put the same budget. Ten pages cannot absorb the link velocity that a serious off-page program generates, so the signals pile onto the homepage and a couple of service pages." },
        { kind: "p", text: "That concentration is the footprint search engines flag as manipulation. The thin site over-optimizes by default: the same spend that lifts a deep site trips the spam filters on a shallow one." },
        { kind: "p", text: "You cannot safely buy a $5,000-a-month off-page program for a business card. The site over-optimizes before the budget does any good." },
        { kind: "definition", term: "Link-absorption capacity", def: "How much off-page authority a site can take on before the signal pattern looks unnatural. It scales with the number of legitimate pages worth linking to. A deep silo structure raises the ceiling; a ten-page brochure keeps it on the floor." },
        { kind: "p", text: "So the sequence is not negotiable: build the asset, then fund the prominence. The deep site is the reservoir that lets a real off-page budget flow in without flooding." },
        { kind: "p", text: "Build prominence on a brochure and you are forcing a fire-hose budget through a garden hose, the pressure shows, and the engine treats the pattern as exactly the manipulation it is. We never touch PBNs, and we never promise a guaranteed #1, because the legitimate program only works on a site deep enough to hold it. The off-page engine itself is the next chapter, [prominence: off-page that moves](/playbook/prominence-off-page)." },
        { kind: "takeaway", text: "Off-page has a capacity limit set by site depth. A **deep site absorbs** a real budget across dozens of legitimate pages; a **thin site over-optimizes** and trips spam filters with the same spend. Build the reservoir before you turn on the hose. No PBNs, ever." },
      ],
    },
    {
      id: "what-this-means",
      h2: "What the asset view means for you",
      navLabel: "What this means",
      blocks: [
        { kind: "p", text: "If you are deciding where the next dollar goes, the frame is not cost, it is ownership. A dollar into ads buys a click and is spent." },
        { kind: "p", text: "A dollar into the site buys a page that ranks, compounds, defends itself for years, and raises the ceiling on every other channel you run. One is consumed." },
        { kind: "p", text: "One accrues. The contractor who treats the website as an expense rents forever and wonders why the budget never compounds. The one who treats it as the asset owns the channel competitors cannot outbid and cannot quickly catch." },
        { kind: "p", text: "None of this asks for faith. We will not promise a guaranteed #1, no honest operator can, and we will not sell you domain age as a ranking factor because it is not one." },
        { kind: "p", text: "What the mechanism guarantees is this: an asset that compounds, a position durability defends, a cost curve that crosses below rented traffic and stays there, and a site deep enough to safely hold the off-page budget that turns a regional player into the regional authority. Promise the floor, project the ceiling, and flag every projection as exactly that." },
        { kind: "takeaway", label: "The honest version", text: "The site is the **engine**, not a line item: it ranks, compounds, defends, and absorbs the prominence budget that lifts everything else. Build the asset first. Then [run the free audit](/audit) and check every claim on this page against your own site." },
      ],
    },
  ],
};
