import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "the-one-thing",
      h2: "What is the one piece you cannot hustle around?",
      navLabel: "The one thing",
      speakable: true,
      blocks: [
        { kind: "p", text: "Nine chapters in, the picture is settled. The ceiling is the owner becoming the bottleneck." },
        { kind: "p", text: "The fix is infrastructure, not more leads. The demand runs on two engines, the proximity-capped map pack and the organic engine that scales, and both of them rank on one foundation underneath." },
        { kind: "p", text: "That foundation is a real, deep website. This chapter narrows everything to a single decision, because in the end there is only one." },
        { kind: "p", text: "Every other lever in this business responds to hustle. You can out-work a thin crew by selling harder." },
        { kind: "p", text: "You can out-work a slow week by knocking on more doors. You can out-work a weak referral month by calling old customers." },
        { kind: "p", text: "Effort moves all of them, because all of them are paid for in your hours, and your hours are yours to spend. The authority website is the one piece that does not work that way." },
        { kind: "p", text: "You cannot hustle a page into ranking. You cannot out-sell a brochure into matching hundreds of searches. The foundation either exists or it does not, and no amount of effort substitutes for building it." },
        { kind: "p", text: "That is the foundation decision. Not which channel, not which tactic, not which month to start." },
        { kind: "p", text: "The decision is whether you build the one asset that produces demand without spending your hours, or whether you keep renting attention and hustling the gap. Everything else is downstream of that answer." },
        { kind: "takeaway", text: "The authority website is **the one piece you cannot hustle around**. Every other lever, sales, doors, referral calls, responds to effort because it is paid for in your hours. The foundation does not. A page either ranks or it does not, and no amount of hustle substitutes for **building the asset**." },
      ],
    },
    {
      id: "why-not-hustle",
      h2: "Why effort fixes everything except the foundation",
      navLabel: "Why not hustle",
      blocks: [
        { kind: "p", text: "Hustle is spending your hours, and your hours reset to zero every morning. That is fine for the levers that are supposed to be spent." },
        { kind: "p", text: "A sales call closes a job and the job is done. A door knocked yields a lead and the lead is worked." },
        { kind: "p", text: "These are transactions: effort in, result out, and tomorrow you do it again. The model works right up to the limit covered in chapter one, where there is no more owner to spend, and then it stalls." },
        { kind: "p", text: "The foundation is the opposite kind of thing. It does not transact, it accumulates." },
        { kind: "p", text: "A page that ranks keeps ranking. It earns clicks while you sleep, produces leads on a Sunday, and answers a buyer's search you never personally touched." },
        { kind: "p", text: "This is why authority cannot be hustled into existence: ranking is not an act, it is a position, and the position is held by depth and time, not by effort in the moment. The data is blunt about the time half." },
        { kind: "p", text: "Across the top ten results, 72.9% of pages are three or more years old, and the average number-one page is five years old (MEASURED). Authority is accumulated time. You cannot sprint accumulated time." },
        { kind: "chart", chart: "page-age" },
        { kind: "p", text: "Stack the two truths and the decision sharpens. The levers you can hustle are spent and gone by morning." },
        { kind: "p", text: "The foundation you cannot hustle is the only one that compounds, and it compounds on a clock that started for your competitors years ago. Every month you spend hustling around the foundation instead of building it is a month their five-year head start grows to six." },
        { kind: "p", text: "The work does not get easier with delay. It gets older." },
        { kind: "comparison",
          leftLabel: "Hustled lever",
          rightLabel: "Built foundation",
          rows: [
            { label: "Paid for in", brochure: "Your hours", system: "Built once", flag: "ILLUSTRATIVE" },
            { label: "Resets each day", brochure: "Yes", system: "No", flag: "ILLUSTRATIVE" },
            { label: "Compounds", brochure: "No", system: "Yes", flag: "ILLUSTRATIVE" },
            { label: "Works while you sleep", brochure: "No", system: "Yes", flag: "ILLUSTRATIVE" },
            { label: "Beaten by effort", brochure: "Yes", system: "No, by depth + time", flag: "MEASURED" },
          ],
        },
      ],
    },
    {
      id: "rent-vs-own",
      h2: "The decision is rent or own",
      navLabel: "Rent or own",
      blocks: [
        { kind: "p", text: "There are only two ways to get a buyer's attention: rent it or own it. Renting is paid ads." },
        { kind: "p", text: "You buy the click, the click arrives, and the moment your card stops the flow stops with it. That is not a flaw, it is the contract." },
        { kind: "p", text: "Paid attention is rented attention, and rented attention disappears the day you stop paying. Owning is the organic engine running on your foundation. You build the page once, it ranks, and it keeps producing whether or not you spend another dollar this month." },
        { kind: "p", text: "Be exact about the trade, because it is not a slogan, it is arithmetic. Ads are not the enemy and nobody is telling you to turn them off." },
        { kind: "p", text: "Ads buy day-one speed and catch the emergency, the searcher who needs a roof tonight and will not wait for you to rank. Run organic and paid together and the total lifts: roughly 50% more clicks and about 27% more conversions than either alone (MEASURED)." },
        { kind: "p", text: "The point is not paid versus organic. The point is that one of them you rent and one of them you own, and only the owned one keeps paying after you stop." },
        { kind: "p", text: "The cost gap is where rent-or-own stops being philosophy. A mature organic lead runs on the order of $30, against roughly $228 for pay-per-click and about $162 for local service ads (MEASURED ranges)." },
        { kind: "p", text: "Organic crosses below paid somewhere around month six (ILLUSTRATIVE, the exact month varies by market). Early on you pay for both, because the foundation is still accumulating and the rent buys you the jobs in the meantime. After it matures, the owned asset carries the load at a fraction of the rented price, and the rent becomes a choice instead of a dependency." },
        { kind: "chart", chart: "mechanism-ledger" },
        { kind: "p", text: "So the foundation decision is the rent-or-own decision wearing different clothes. Rent forever and you never stop paying for attention you do not keep." },
        { kind: "p", text: "Build once and you own the channel that compounds, with rent on top by choice for speed and the emergency. The chapter on [organic versus ads](/playbook/organic-vs-ads) lays the full ledger out side by side." },
      ],
    },
    {
      id: "what-you-are-building",
      h2: "What the foundation actually is",
      navLabel: "What you build",
      blocks: [
        { kind: "p", text: "Strip the abstraction. The foundation is a deep, real website, and the depth is the difference between a brochure and an engine." },
        { kind: "p", text: "A typical brochure ships around ten pages and ranks for your name and your home city, finding no one new. Our live reference build ships 147 pages (MEASURED), and every one of them is a doorway pointed at a distinct search a real buyer actually types." },
        { kind: "p", text: "That is more than a tenfold difference in the number of queries the site can match, and you do not out-rank a deeper site by polishing ten pages. You match the searches it matches, or you do not appear." },
        { kind: "definition", term: "The foundation", def: "A deep authority website: a page for every real service-in-a-town search, answer-first pages for the cost and comparison questions buyers ask, machine-readable structure for every crawler and AI extractor, and clean technical performance underneath, built once and accumulating rank from day one." },
        { kind: "p", text: "Depth is not the only axis. The foundation has to be legible to the new judges of attention, because the search page is changing under everyone's feet." },
        { kind: "p", text: "AI Overviews cut top-result clicks from about 34.5% in April 2025 to roughly 58% by December 2025 (MEASURED), and around 60% of searches now end without a click at all (MEASURED). A page cited in an AI answer earns about 35% more organic clicks (MEASURED), and 88% of AI-cited URLs do not rank in the top ten (MEASURED), which means AI is its own surface with its own door. The foundation is built to be cited there, not just ranked below the fold." },
        { kind: "chart", chart: "gap-wall" },
        { kind: "p", text: "And the depth has to be real, which is the hard guardrail of the entire program. A page per town that swaps the city name into the same paragraph is a doorway page, and Google has spent years learning to ignore it. Every page carries something true and specific to the work it claims." },
        { kind: "antiDoorway" },
      ],
    },
    {
      id: "why-it-rarely-gets-built",
      h2: "Why almost nobody builds it",
      navLabel: "Why it's rare",
      blocks: [
        { kind: "p", text: "If the foundation is the one piece that breaks the ceiling, the obvious question is why so few contractors have one. The answer is not that they are lazy." },
        { kind: "p", text: "It is that the foundation is exactly the kind of work hustle cannot reach. It does not pay off this week, it pays off across years." },
        { kind: "p", text: "It cannot be willed into existence by effort, it has to be built and then left to accumulate. Every instinct that made a contractor good at the trade, move fast, fix it today, out-work the problem, points the wrong way on this one task." },
        { kind: "p", text: "So the field reflects the difficulty. Roughly 27% of contractors have no dedicated site at all (MEASURED)." },
        { kind: "p", text: "Among the ones that do, 94.8% fail basic accessibility standards and about 52% fail Core Web Vitals (MEASURED), and an estimated 96% ship no LocalBusiness schema (MODELED), which is the structured data that tells a machine what the business even is. The market is a wall of brochures, and the brochure is what you get when you treat the foundation like a thing you can knock out in a weekend instead of an asset you build to a standard." },
        { kind: "p", text: "That difficulty is the opportunity, stated plainly. The reason the foundation breaks the ceiling is the same reason almost nobody has one: it cannot be hustled, so the field never built it, so the contractor who does build it stands nearly alone on the surface that compounds." },
        { kind: "p", text: "Scarcity is not a side effect here. It is the entire return." },
        { kind: "p", text: "You are not racing a crowded field. You are stepping onto an empty one." },
        { kind: "takeaway", label: "The opportunity", text: "The foundation is rare for the same reason it works: **it cannot be hustled.** The field is a wall of brochures, 27% have no site at all, 94.8% fail accessibility, ~96% ship no schema. The contractor who builds the asset stands nearly alone on the surface that compounds. **Scarcity is the return.**" },
      ],
    },
    {
      id: "what-king-maker-does",
      h2: "This is what King Maker builds and runs for you",
      navLabel: "What we do",
      blocks: [
        { kind: "p", text: "Here is the close. The foundation is the one piece you cannot hustle around, it is the asset that breaks the ceiling, and it is the work almost nobody does because effort does not move it." },
        { kind: "p", text: "That is precisely the piece King Maker builds and runs, done for you. We build the deep authority site, the page for every real search, the answer-first pages for the cost and comparison questions, the machine-readable structure for every crawler and AI extractor, the clean technical foundation underneath, to the standard the rest of the field fails." },
        { kind: "p", text: "Done for you is the operative phrase, because the reason this work goes undone is that it sits outside the contractor's hours and instincts. You keep doing the thing you are good at, the trade, the crew, the customer in the room." },
        { kind: "p", text: "We carry the one piece you cannot hustle, build it once to a real standard, and run it so it keeps accumulating. The foundation is the floor: it removes the owner as the constraint and gives both engines something real to rank." },
        { kind: "p", text: "It is not a promise of a number, and anyone who guarantees you a number or a position is selling you something. We promise the floor and project the ceiling from there." },
        { kind: "p", text: "The decision narrows to one line. You can keep renting attention and hustling the gap, or you can own the asset that compounds while your competitors' five-year head start grows another year." },
        { kind: "p", text: "The first option never stops costing you. The second one you build once. There is no third option where effort substitutes for the foundation, because the foundation is the one place effort does not reach." },
        { kind: "p", text: "Make the decision with your own numbers in front of you. Run your current site through the [audit](/audit) and count how many of your pages match a real search, then read [the asset, your website](/playbook/the-asset-your-website) for the full page-count math or [why a brochure can't win](/guides/why-a-brochure-cant-win) for the depth argument in detail." },
        { kind: "p", text: "The foundation is the one thing you cannot hustle around. Build it, or keep paying rent on attention you never get to keep." },
      ],
    },
  ],
};
