import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "the-roadmap",
      h2: "How does a contractor go from $1M to $10M?",
      navLabel: "The roadmap",
      speakable: true,
      blocks: [
        { kind: "p", text: "You do not go from one million to ten by working harder. You went from zero to one by working harder, and that is precisely the engine that runs out at the ceiling." },
        { kind: "p", text: "The path to ten million is a sequence, not an effort. It runs in four phases, and the phases are ordered for a reason: each one builds the layer the next one needs." },
        { kind: "p", text: "Skip a phase and you build on sand. Reverse two and you spend money on a fire you have nothing to feed." },
        { kind: "p", text: "The order is the strategy. Phase one builds the asset: a deep authority website that can rank for the hundreds of real searches a buyer types." },
        { kind: "p", text: "Phase two earns prominence: the off-page weight and the review velocity that make the asset trusted. Phase three converts that trust into organic regional dominance: ranking across the whole region, not just the home city." },
        { kind: "p", text: "Phase four expands the territory: satellite locations that plant the same machine in new ground. Foundation, then prominence, then dominance, then expansion. In that order, every time." },
        { kind: "p", text: "The reason the order cannot move is mechanical. Off-page weight pointed at a brochure ranks a brochure, and a brochure has ten doorways pointed at a market that is hundreds of searches wide, so the weight is wasted on pages that match almost nothing." },
        { kind: "p", text: "Regional dominance is impossible without pages for the region to dominate. Expansion before dominance just clones a business that has not proven it can win its own backyard." },
        { kind: "p", text: "Each phase is the precondition for the next. That is why this is a roadmap and not a menu." },
        {
          kind: "list",
          ordered: true,
          items: [
            "Phase 1: Foundation. Build the authority website: the deep, real asset that can rank for the hundreds of searches a buyer types. This is the layer everything else runs on.",
            "Phase 2: Prominence. Earn off-page weight and review velocity so the asset is trusted, not just present. Trust is what turns a ranked page into a ranking page.",
            "Phase 3: Regional dominance. Convert that trust into organic ranking across the whole region, not just the home city. This is the engine that scales past proximity.",
            "Phase 4: Territory expansion. Plant satellite locations and clone the proven machine into new ground. Expansion last, because you only clone what already wins.",
          ],
        },
        { kind: "takeaway", text: "Four phases, fixed order: **foundation, prominence, dominance, expansion**. Each phase is the precondition for the next. Off-page weight pointed at a brochure ranks a brochure. You only clone a machine that already wins. The order is the strategy, and the order does not move." },
      ],
    },
    {
      id: "phase-1-foundation",
      h2: "Phase 1: Build the foundation, an authority website",
      navLabel: "Phase 1: Foundation",
      blocks: [
        { kind: "p", text: "Phase one builds the asset, because every other phase runs on it. The asset is not a brochure." },
        { kind: "p", text: "A brochure ships around ten pages, ranks for your name and your home city, and finds no one new. The authority site is a different kind of thing entirely: a deep set of pages, one per real search a buyer types, so the site can match demand that is hundreds of searches wide instead of ten. Our live reference build ships 147 pages against the typical brochure's ten, more than a tenfold difference in the number of distinct searches the site can answer." },
        { kind: "chart", chart: "trade-table" },
        { kind: "p", text: "The depth has to be real, and this is the line that separates the asset from the scam. A page per town that swaps the city name into the same paragraph is a doorway page, and Google has spent years learning to ignore it. Every page must carry something true and specific to the work it claims, or it does not count and, worse, it drags the rest of the site down with it." },
        { kind: "antiDoorway" },
        { kind: "p", text: "There is a hard timeline truth here, and the honest builder says it out loud. The foundation is the slow part." },
        { kind: "p", text: "Authority is accumulated time: across top-ranking pages, 72.9% of the top-10 results are three or more years old, and the average page sitting at position one is roughly five years old. You cannot buy your way past that, and you cannot rush it." },
        { kind: "p", text: "What phase one does is start the clock and build the thing that earns from the clock running. The page you publish this month is not ranking next month." },
        { kind: "p", text: "It is ranking in year two, and it keeps ranking after that. The floor of phase one is a real, indexable asset. The ceiling is what time does to it." },
        { kind: "chart", chart: "page-age" },
        { kind: "p", text: "This is the phase the whole roadmap stands on, so it gets its own chapter. See [the asset, your website](/playbook/the-asset-your-website) for the full anatomy of what gets built, and [the foundation decision](/playbook/the-foundation-decision) for why this is the one decision that gates the other three." },
      ],
    },
    {
      id: "phase-2-prominence",
      h2: "Phase 2: Earn prominence with off-page weight and reviews",
      navLabel: "Phase 2: Prominence",
      blocks: [
        { kind: "p", text: "A built site is not a trusted site. Phase two earns the trust." },
        { kind: "p", text: "The asset from phase one is real and indexable, but it is unproven, and an unproven page ranks below a proven one no matter how good the page is. Prominence is the off-page weight that proves it: relevant links earned from real sources, consistent citations across the places that list local businesses, and a steady, accumulating stream of genuine reviews. This is the work that turns a ranked page into a ranking page." },
        { kind: "p", text: "Reviews are the fastest-moving lever in this phase, so they get the discipline. Review velocity, the steady rate of fresh reviews over time, moves prominence faster than almost anything else you can do off-page, because it is the signal that the business is alive, busy, and trusted right now." },
        { kind: "p", text: "A site with depth and a thin trickle of reviews loses to a shallower competitor with a steady stream, and that is fair, because the steady stream is the truer signal. The work is operational: a real process that earns a review from a real job, every job, every time." },
        { kind: "p", text: "Two hard guardrails, because the shortcuts in this phase are the ones that get businesses penalized. No PBNs, ever." },
        { kind: "p", text: "A private blog network is a fabricated link source, Google is exceptional at detecting them, and the penalty erases the asset you spent phase one building. And if you are in a storm market, every word touching insurance stays compliant: no guaranteed-claim language, no public-adjuster offers, no zero-deductible promises. The prominence is earned the slow, real way, or it is a liability you are building on top of your asset instead of a foundation under it." },
        { kind: "takeaway", text: "Prominence is **earned, not bought**. Off-page weight turns a ranked page into a ranking page, and **review velocity** is the fastest lever you have. The shortcuts, PBNs and fabricated authority, do not accelerate this phase, they detonate the asset phase one built. Earn it the real way." },
        { kind: "p", text: "The prominence layer is its own discipline with its own chapter. See [prominence, off-page](/playbook/prominence-off-page) for the ranked levers and the order to pull them in." },
      ],
    },
    {
      id: "phase-3-dominance",
      h2: "Phase 3: Convert trust into organic regional dominance",
      navLabel: "Phase 3: Dominance",
      blocks: [
        { kind: "p", text: "Phase three is where the asset starts to pay. A deep site with earned prominence does not rank for one search, it ranks across a region, and regional organic dominance is the engine that finally breaks the proximity ceiling." },
        { kind: "p", text: "Understand why that matters: the map pack is capped at roughly five miles, and it yields on the order of one to two jobs a month early on (the shape of that, not a guaranteed count), maturing toward something nearer ten a month only at a roughly two-year ceiling. You cannot scale a multi-million-dollar business on a five-mile radius." },
        { kind: "p", text: "Organic has no such cap. It is limited only by how many real searches your site can answer, and phase one built it to answer hundreds." },
        { kind: "chart", chart: "matrix" },
        { kind: "p", text: "Dominance is where the long-tail math turns from a liability into a moat. Most search demand is not the one fat keyword everyone fights over; 95% of all queries get ten or fewer searches a month, and 96.55% of all web pages get zero Google traffic because they were never built to match a real search in the first place." },
        { kind: "p", text: "The deep site wins precisely there: it owns the thousand small, specific searches the brochure never built a page for, and a thousand small searches answered is a far larger, far steadier flow than one big keyword contested. This is organic's real edge." },
        { kind: "p", text: "It does not win on a higher click-conversion rate. It wins on cost, on durable volume, and on trust, and those compound while paid does not." },
        { kind: "chart", chart: "long-tail" },
        { kind: "p", text: "There is a second front opening in this phase, and ignoring it costs you. AI answer surfaces now sit on top of search, and they are their own surface." },
        { kind: "p", text: "AI Overviews cut clicks to the top organic result from roughly 34.5% in April 2025 to roughly 58% by December 2025, and around 60% of searches now end without a click at all. But a page cited in those answers earns about 35% more organic clicks, and notably 88% of AI-cited URLs do not rank in the top ten, which means the AI surface is winnable on its own terms by a deep, well-structured site even where the blue-link rank is still maturing. Dominance in 2026 means ranking the region and getting cited, both." },
        { kind: "p", text: "The two on-page engines split this work, and the split is worth knowing cold. See [organic versus the map pack](/playbook/organic-vs-the-map-pack) for how proximity and research divide between the pack and organic, and [organic versus ads](/playbook/organic-vs-ads) for where paid buys the speed organic takes time to earn." },
      ],
    },
    {
      id: "phase-4-expansion",
      h2: "Phase 4: Expand the territory with satellite locations",
      navLabel: "Phase 4: Expansion",
      blocks: [
        { kind: "p", text: "Phase four is the last one for a reason: you only clone a machine that already wins. By the time a contractor has organic regional dominance, the home market is producing demand the business controls, on assets that compound, without spending the owner's hours to produce it." },
        { kind: "p", text: "That is the thing worth replicating. A satellite location is not a second roll of the dice. It is the same proven machine, the deep authority site and the earned prominence and the regional dominance, planted in new ground where it has not been built yet." },
        { kind: "p", text: "Each satellite restarts the clock locally, and the honest builder names that. A new territory does not inherit the home market's accumulated authority; it earns its own, on its own timeline, the same slow way phase one did." },
        { kind: "p", text: "What the satellite inherits is the playbook, the team that has run it once, and the proof that the sequence works. That is an enormous head start, but it is a head start, not a teleport. You are running phases one through three again in a new market, faster because you have done it, but not instantly." },
        { kind: "p", text: "This is also how the math reaches eight figures, because a single market has a ceiling and the model does not. One market, fully dominated, is a strong seven-figure business." },
        { kind: "p", text: "Ten million is several markets each running the same compounding machine, which is exactly why expansion is last: every satellite is only as good as the playbook it clones, and the playbook is the three phases that came before it. Expand a winning machine and you multiply. Expand a business that has not won its own backyard and you have multiplied a problem." },
        { kind: "takeaway", text: "Expansion is **last** because you only clone a machine that already wins. A satellite is the proven playbook planted in new ground, not a second gamble. It **restarts the clock locally** (it earns its own authority on its own timeline), but it inherits the team, the system, and the proof. Several markets running the compounding machine is how the number reaches eight figures." },
        { kind: "p", text: "The expansion playbook is its own chapter. See [satellite expansion](/playbook/satellite-expansion) for how to plant a new market without diluting the home one, and [the infrastructure of a $5M contractor](/playbook/infrastructure-of-a-5m-contractor) for what has to be running internally before you clone it." },
      ],
    },
    {
      id: "the-timeline",
      h2: "The honest timeline: promise the floor, project the ceiling",
      navLabel: "The honest timeline",
      blocks: [
        { kind: "p", text: "Here is the part most people selling this leave out, so it goes first. None of these phases is fast, and the foundation is the slowest of all." },
        { kind: "p", text: "Authority is accumulated time: the average page at position one is roughly five years old, and 72.9% of the top-10 are three or more years old. The page you publish this month is ranking in year two, not next month." },
        { kind: "p", text: "Anyone who promises you top rankings in ninety days is either ignorant of how this works or counting on you to be. The real timeline is measured in years, and the early months are spent building assets that have not started paying yet." },
        { kind: "p", text: "The floor is what the work guarantees. Phase one guarantees a real, deep, indexable asset that did not exist before, a site built to match hundreds of real searches instead of ten." },
        { kind: "p", text: "Phase two guarantees earned prominence, accumulating instead of fabricated. Phase three guarantees the region is covered with pages that can rank as the clock runs." },
        { kind: "p", text: "Those are deliverables, not hopes. What no honest builder guarantees is a specific revenue number on a specific date, because the ceiling depends on the market, the operations, and time, and pretending otherwise is the sale of a number nobody can deliver." },
        { kind: "debunk", myth: "Build the site and the leads come in ninety days.", reality: "The foundation is the slowest phase, and ranking is measured in years. The average #1 page is about five years old; 72.9% of the top-10 are 3+ years old.", why: "Authority is accumulated time, and time cannot be bought or rushed. What ninety days buys you is a built asset that has started the clock, not a ranked one. The page published now ranks in year two and keeps ranking after." },
        { kind: "p", text: "So the discipline is simple and it is the whole posture: promise the floor, project the ceiling. The floor is the asset and the system, delivered, every time." },
        { kind: "p", text: "The ceiling is what time and dominance and expansion do to a business that has removed the owner as the constraint, and the ceiling is real, but it is a projection, not a promise. The contractor who reaches ten million is not the one who found a faster timeline." },
        { kind: "p", text: "He is the one who started the slow phase first and let it run. Start where the whole roadmap starts: read [the foundation decision](/playbook/the-foundation-decision), or run your current site through the [audit](/audit) and count how many of your pages match a real search." },
      ],
    },
  ],
};
