import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "the-ceiling",
      h2: "Why do most contractors stall at $1-2M?",
      navLabel: "The ceiling",
      speakable: true,
      blocks: [
        { kind: "p", text: "Most contractors stall at the same place: somewhere between one and two million in revenue, the line stops climbing and starts flattening. Not because the work got worse." },
        { kind: "p", text: "Not because the market dried up. The work is good, the reviews are real, the trucks are busy. The number stalls because the machine that produced it has hit the limit of what it was built to produce, and nothing about working harder moves that limit." },
        { kind: "p", text: "The first million is built on the owner. The owner sells the job, runs the crew, answers the phone, and chases the referral." },
        { kind: "p", text: "That works, and it works well, right up to the point where there is no more owner to spend. A person is a fixed amount of hours." },
        { kind: "p", text: "When every hour is already committed, the business cannot grow by adding more of the thing that built it, because the thing that built it was one person, and that person is full. The ceiling is not a revenue number. It is the moment the founder becomes the bottleneck." },
        { kind: "p", text: "This is the most common mistake at the ceiling: the owner reads the flatline as a marketing problem and goes looking for more leads. More leads do not fix it." },
        { kind: "p", text: "The lead is not the constraint. The constraint is that there is no system underneath the owner that can take a lead and turn it into a job without the owner in the middle of it." },
        { kind: "p", text: "You do not have a marketing problem. You have an infrastructure problem." },
        { kind: "takeaway", text: "The ceiling is not a revenue number, it is the moment the **owner becomes the bottleneck**. The first million is built on the founder's hours. A person is a fixed amount of hours, so the business that grows by adding more founder runs out of founder. You do not have a marketing problem. You have an **infrastructure problem**." },
      ],
    },
    {
      id: "owner-is-the-machine",
      h2: "At the ceiling, the owner is the machine",
      navLabel: "Owner is the machine",
      blocks: [
        { kind: "p", text: "Walk through a $1.5M contractor and you find the same shape every time. The owner is the salesperson, so every estimate waits on his calendar." },
        { kind: "p", text: "The owner is the closer, so every job that converts converts because he was in the room. The owner is the quality check, the dispatcher, and the relationship the customer actually trusts." },
        { kind: "p", text: "The business does not have a sales process. It has a person who is good at selling, and that person is one person." },
        { kind: "p", text: "Lead flow looks just as fragile under the same light. It is referrals plus a thin website, and that is the whole of it." },
        { kind: "p", text: "Referrals are excellent jobs and they convert, but they arrive when they arrive. You cannot turn them up." },
        { kind: "p", text: "You cannot forecast them. They are a function of past work, not a channel you control." },
        { kind: "p", text: "And the website that sits next to them is a brochure: it confirms you exist to the handful of people who already heard your name, and it finds no one new. It is not a demand engine. It is a digital business card." },
        { kind: "p", text: "Stack those two facts and the ceiling explains itself. Demand you cannot control, met by capacity that is one human being." },
        { kind: "p", text: "Every part of the business routes through the founder, and unpredictable referral flow gives him nothing steady to build a system around. The business is not under-marketed." },
        { kind: "p", text: "It is under-built. There is no layer between the owner and the work that can carry load when the owner is full." },
        {
          kind: "comparison",
          leftLabel: "Founder-run",
          rightLabel: "System-run",
          rows: [
            { label: "Who sells the job", brochure: "Owner", system: "Process", flag: "ILLUSTRATIVE" },
            { label: "Lead source", brochure: "Referrals", system: "Owned channels", flag: "ILLUSTRATIVE" },
            { label: "The website", brochure: "Brochure", system: "Engine", flag: "MEASURED" },
            { label: "Demand control", brochure: "None", system: "Forecastable", flag: "ILLUSTRATIVE" },
            { label: "Grows by adding", brochure: "Founder hours", system: "Pages + crews", flag: "ILLUSTRATIVE" },
          ],
        },
      ],
    },
    {
      id: "not-marketing-infrastructure",
      h2: "It's an infrastructure problem, not a marketing problem",
      navLabel: "Infrastructure, not marketing",
      blocks: [
        { kind: "p", text: "The reframe is the entire chapter, so be precise about it. A marketing problem is a shortage of leads." },
        { kind: "p", text: "An infrastructure problem is the absence of a system that turns demand into jobs without the owner inside every step. They feel identical from behind the desk, because both show up as a flat revenue line, but they have opposite fixes." },
        { kind: "p", text: "Buy leads into a business with no system and you have bought yourself more work to do personally. The bottleneck does not move. It just gets more crowded." },
        { kind: "definition", term: "Infrastructure", def: "The owned, repeatable layer that produces and converts demand without the founder in the middle of every step: a site that ranks for real searches, a process that handles a lead the same way every time, and capacity that can take the job once it lands." },
        { kind: "p", text: "Infrastructure is the thing that compounds. A founder's hours do not compound; they reset to zero every morning and you spend them again." },
        { kind: "p", text: "A page that ranks does not reset. It keeps ranking, keeps earning clicks, and keeps producing leads while the owner sleeps." },
        { kind: "p", text: "This is the structural difference between a business that plateaus and one that climbs: one runs on a resource that is spent and gone, the other runs on assets that accumulate. The contractor who breaks the ceiling is not the one who found more leads. He is the one who built the layer the leads flow through." },
        { kind: "chart", chart: "compounding" },
        { kind: "p", text: "There is a hard, honest line here. Infrastructure is the floor, not a guarantee of the ceiling." },
        { kind: "p", text: "Building the system does not promise a specific revenue number, and anyone who promises you one is selling you something. What the system does is remove the owner as the constraint, so growth becomes possible at all." },
        { kind: "p", text: "You cannot project a ceiling onto a business that has no floor under it. First you build the layer that can carry load. Then the number can move." },
      ],
    },
    {
      id: "two-engines",
      h2: "Two engines run the demand: the pack and organic",
      navLabel: "The two engines",
      blocks: [
        { kind: "p", text: "Demand you control comes from two engines, and they do different jobs. Confusing them is how contractors waste years." },
        { kind: "p", text: "The map pack is the local three results that sit at the top of a search with the map. Organic is the ranked blue links below it, the deep set of pages that answer the hundreds of distinct searches a real buyer types. They are not the same engine, they catch different demand, and you need both pointed at the right thing." },
        { kind: "p", text: "The map pack is proximity-capped. It serves the searcher who is physically near you, roughly within five miles, and that radius is a ceiling you cannot buy your way past." },
        { kind: "p", text: "Early on, the pack yields on the order of one to two jobs a month (the shape of that, not a guaranteed count), maturing toward something nearer ten a month only at a roughly two-year ceiling. It is real and it catches the nearby and the urgent. It is also small, and it does not scale, because you cannot move your office five miles in every direction at once." },
        { kind: "p", text: "Organic is the engine that scales. It is not capped by how close the buyer stands." },
        { kind: "p", text: "It is capped only by how many real searches your site can answer, and that you can build. Every page that ranks for a service in a town, a cost question, a comparison, is another doorway pointed at demand the pack will never reach." },
        { kind: "p", text: "This is the engine that wins the considered, researched purchase: the buyer who is comparing, reading, and building a shortlist over weeks before anyone signs. Organic does not win on a higher click-conversion rate. It wins on cost, on durable volume, and on trust, and those compound." },
        { kind: "chart", chart: "mechanism-ledger" },
        { kind: "p", text: "Run them together and assign them their jobs. The pack catches proximity." },
        { kind: "p", text: "Organic wins the research. Paid ads, which we treat as their own lever, buy day-one speed and catch the emergency before any of it has matured. Each engine is detailed in its own chapter: see [organic versus the map pack](/playbook/organic-vs-the-map-pack) for how the two on-page engines split the work, and [organic versus ads](/playbook/organic-vs-ads) for where paid earns its place." },
      ],
    },
    {
      id: "the-asset",
      h2: "The website is the asset that breaks the ceiling",
      navLabel: "The asset",
      blocks: [
        { kind: "p", text: "Both engines run on the same foundation: the site. The pack and organic are surfaces, but the thing that earns a position on either one is a real, deep website underneath." },
        { kind: "p", text: "This is why the website is not a marketing expense to minimize. It is the single asset most likely to break the ceiling, because it is the layer that produces demand without spending the owner's hours to do it." },
        { kind: "p", text: "A brochure cannot do that job. A brochure has ten pages, ranks for your name and your home city, and finds no one new. The system that breaks the ceiling is a different kind of site entirely." },
        { kind: "p", text: "The difference is not cosmetic, it is structural. A typical brochure ships around ten pages." },
        { kind: "p", text: "Our live reference build ships 147, more than a tenfold difference in the number of distinct searches the site can match. Depth is the whole point: every page is a doorway pointed at a real query a buyer actually types, and the brochure has ten doorways while real demand is hundreds of searches wide." },
        { kind: "p", text: "You do not out-rank a deeper site by polishing ten pages. You match the searches it matches, or you do not appear at all." },
        { kind: "chart", chart: "trade-table" },
        { kind: "p", text: "Two guardrails, because honesty is the moat. First, the depth has to be real." },
        { kind: "p", text: "A page per town that swaps the city name into the same paragraph is a doorway page, and Google has spent years learning to ignore it. Every page must carry something true and specific to the work it claims." },
        { kind: "antiDoorway" },
        { kind: "p", text: "Second, none of this is a promise of a number. Building the asset removes the owner as the constraint and gives the two engines something real to rank." },
        { kind: "p", text: "That is the floor. The ceiling is yours to build from there. Next, see [where high-ticket jobs come from](/playbook/where-high-ticket-jobs-come-from) to trace the buyer's actual path, read [why a brochure can't win](/guides/why-a-brochure-cant-win) for the page-count math in full, or run your own site through the [audit](/audit) and count how many of your pages match a real search." },
      ],
    },
  ],
};
