import type { GuideContent } from "@/lib/content-blocks";

export const content: GuideContent = {
  sections: [
    {
      id: "the-considered-buyer",
      h2: "Where do high-ticket jobs come from?",
      navLabel: "The considered buyer",
      speakable: true,
      blocks: [
        { kind: "p", text: "High-ticket jobs come from the considered buyer, and the considered buyer does not behave the way a cheap job behaves. A roof replacement, a full HVAC system, a kitchen remodel: these are five-figure decisions a homeowner makes a few times in a lifetime." },
        { kind: "p", text: "Nobody spends that money on the first name they see. They research." },
        { kind: "p", text: "They open Google, they read, they compare, and somewhere in that process they decide who is trustworthy enough to let into their home with a five-figure invoice. The job goes to whoever earned that trust during the research. That is the entire game." },
        { kind: "p", text: "Watch what the considered buyer actually does on the page. They skip the ads." },
        { kind: "p", text: "They skip the map pack. They scroll to the first real organic result, because they have learned that the ad is a paid placement and the map is a proximity list, and neither one is the same as being the best." },
        { kind: "p", text: "The result that ranks #1 organically reads as the one Google decided earned the top spot. For a decision this size, the buyer wants the earned answer, not the bought one. So the click goes to organic, and the job follows the click." },
        { kind: "takeaway", text: "High-ticket jobs are **researched, not impulse-bought**. The considered buyer skips the ad, skips the map, and trusts the **#1 organic result** because it reads as earned. The contractor who owns that result owns the considered job before a phone ever rings." },
      ],
    },
    {
      id: "why-they-trust-organic",
      h2: "Why the considered buyer trusts the #1 organic result",
      navLabel: "Why organic wins trust",
      blocks: [
        { kind: "p", text: "Trust is the whole transaction at this ticket size, and the buyer reads the search page as a trust signal. An ad says someone paid to be there." },
        { kind: "p", text: "The map pack says someone is close. Neither answers the question the buyer is actually asking, which is who is the best." },
        { kind: "p", text: "The #1 organic result is the closest thing on the page to an answer to that question, because the buyer believes Google sorted on merit. Whether or not that belief is technically precise, it governs the click. The buyer behaves as if rank equals quality, and that behavior is what sends the considered job to the top organic result." },
        { kind: "p", text: "This is why the shortlist forms early and forms small. **78% of buyers shortlist three vendors or fewer**, and **95% of them pick a name that was on the shortlist from day one.** The shortlist is built during the research, from the results the buyer keeps landing on." },
        { kind: "p", text: "If your pages are the ones that answered the cost question and the comparison question, your name is on the list before you ever speak. If you were not found during the research, you are not on the list, and the job is decided without you in the room." },
        { kind: "p", text: "There is no losing bid. You simply never made the cut." },
        { kind: "p", text: "The research window is long enough for this to play out fully. A considered home-improvement decision can run on the order of **~94 days** before anyone signs (illustrative, the window varies widely by ticket and trade), and B2B-scale projects average far longer." },
        { kind: "p", text: "For weeks the buyer is reading and comparing. The contractor whose pages are present for that entire window earns the trust by attrition: showing up, answering the next question, being the result that keeps appearing." },
        { kind: "p", text: "That presence is not bought in an auction. It is accumulated on the page." },
        { kind: "takeaway", label: "The mechanism", text: "Rank reads as merit. The buyer treats the **#1 organic result** as the earned answer, builds a **three-name shortlist** from the pages they keep landing on, and picks from that list. Be the page they land on, or be invisible during the only window that decides the job." },
      ],
    },
    {
      id: "the-intent-spectrum",
      h2: "The intent spectrum: emergency on one end, planned replacement on the other",
      navLabel: "The intent spectrum",
      blocks: [
        { kind: "p", text: "Not every job is researched, and pretending otherwise loses money. Demand runs along a spectrum of intent." },
        { kind: "p", text: "On one end is the emergency: a tree through the roof at 2am, no heat in January, water coming through the ceiling. That buyer is not researching." },
        { kind: "p", text: "They are calling the first credible name that answers, and they will pay a premium for speed. On the other end is the planned replacement: the homeowner who knows the roof has five years left and is doing the math now." },
        { kind: "p", text: "That buyer is deep in research, comparing for weeks, and price-shopping the considered way. These are different people with different behavior, and they are caught by different surfaces." },
        { kind: "p", text: "The emergency is caught by the call and the proximity. When the storm hits, the buyer types the urgent query and dials whoever shows up first and credible." },
        { kind: "p", text: "Ads catch this buyer because the auction puts you at the top the instant they search, with no waiting for rank to accumulate. The map pack catches the slice of this buyer who is close enough, because the pack is proximity-capped to roughly **five miles** and rewards being near. This is the emergency slice: real revenue, won on speed, not on depth." },
        { kind: "p", text: "The planned replacement is caught by the page. This buyer has time, so they spend it researching, and they reward the contractor whose site answered the questions they were already asking." },
        { kind: "p", text: "This is the considered job, the high-ticket job, and it is won the slow way: a page for the service in their town, a page for the cost question, a page for the comparison they are running in their head. The emergency buyer never reads those pages." },
        { kind: "p", text: "The planned buyer reads nothing else. A real business catches both ends, with the right surface pointed at each: the call and the ads earn the emergency, the depth earns the considered job, the pack catches the proximity in between." },
        {
          kind: "comparison",
          leftLabel: "Emergency / storm",
          rightLabel: "Planned replacement",
          rows: [
            { label: "Buyer behavior", brochure: "Calls now", system: "Researches for weeks", flag: "MEASURED" },
            { label: "What wins it", brochure: "Speed", system: "Trust + depth", flag: "MEASURED" },
            { label: "Surface that catches it", brochure: "Ads / call", system: "Organic pages", flag: "MEASURED" },
            { label: "Reads cost / comparison pages", brochure: "No", system: "Yes", flag: "MEASURED" },
            { label: "Ticket size", brochure: "Premium for speed", system: "Considered high-ticket", flag: "MODELED" },
          ],
        },
        { kind: "takeaway", text: "Match the surface to the intent. **Ads and the call earn the emergency.** The **map pack catches proximity** inside ~5 miles. **Organic depth earns the considered, high-ticket job.** One surface cannot catch the whole spectrum, so a real business runs all three with the right one pointed at each end." },
      ],
    },
    {
      id: "the-zero-pack-long-tail",
      h2: "Most high-ticket demand never touches the map pack",
      navLabel: "The zero-pack long-tail",
      blocks: [
        { kind: "p", text: "Here is the part most contractors never see. The considered buyer does not search the way the map pack is built to answer." },
        { kind: "p", text: "The pack answers the broad, generic query, the one-word service plus the city, and it answers it for the handful of businesses physically nearest the searcher. But that is a thin slice of the demand." },
        { kind: "p", text: "The considered buyer types the long, specific question: the material, the cost, the comparison, the named town that is not the one your office sits in. Those queries do not trigger a map pack at all, or they trigger one that does not reach the buyer. The job lives entirely in the organic results below it." },
        { kind: "chart", chart: "long-tail" },
        { kind: "p", text: "The numbers explain why depth, not proximity, owns this demand. **95% of search queries get 10 or fewer searches a month.** Each long-tail question looks like nothing on its own." },
        { kind: "p", text: "Added together they are the entire considered market, and they are scattered across hundreds of distinct phrasings the buyer actually types. The map pack cannot answer hundreds of distinct queries." },
        { kind: "p", text: "It answers a few broad ones, for the few businesses nearby. Everything else, the bulk of the considered demand, is won on the page or not won at all." },
        { kind: "p", text: "And here is the consequence that decides who gets these jobs: **96.55% of all web pages get zero traffic from Google.** Not low. Zero." },
        { kind: "p", text: "A page is live and no one ever lands on it, because it was never built to answer a query anyone types. A brochure's pages are exactly these pages, describing the business in general terms, matching no specific search, sitting at zero while the considered buyer scrolls past to the contractor who built the page that answers the actual question. The long tail is a wall of low-volume, zero-pack queries, and you win it the only way it can be won: one real page per band of demand, each answering one question better than anyone else." },
        { kind: "takeaway", label: "The honest version", text: "The map pack catches the few **broad, nearby** searches. The considered, high-ticket job lives in the **long tail**, hundreds of low-volume questions the pack never answers. **95% of queries get 10 or fewer searches a month**, and **96.55% of pages get zero Google traffic**, because they were never built to match a real query. Depth wins the tail. Proximity cannot." },
      ],
    },
    {
      id: "where-the-money-is",
      h2: "Where the high-ticket money actually concentrates",
      navLabel: "Where the money is",
      blocks: [
        { kind: "p", text: "Put the spectrum and the long tail together and the picture is plain. The emergency slice is real and worth catching, but it is a slice, won on speed and capped by proximity." },
        { kind: "p", text: "The map pack early on yields on the order of **one to two jobs a month** (modeled, claim the shape not the count), maturing toward roughly ten a month only at a two-year ceiling, and only inside its five-mile radius. You cannot build a five-million-dollar business on a five-mile circle. The volume is not there, and the radius does not stretch." },
        { kind: "p", text: "The considered, high-ticket job is where the money concentrates, and it is won in the organic results across the long tail. That is the job the buyer researches for weeks, shortlists to three names, and pays a five-figure invoice for." },
        { kind: "p", text: "It is decided by which contractor's pages were present and trusted during the research window. The pack catches proximity, ads catch the emergency, and depth catches the considered job, the largest and most durable share of high-ticket revenue. Spend accordingly: a real business runs ads for speed and builds depth for the considered job, because that is where the volume and the margin live." },
        { kind: "takeaway", text: "The **considered organic job** is the prize: researched for weeks, shortlisted to three, paid at a five-figure ticket, and won on the page. The pack and ads catch the edges; **depth catches the center.** That is where high-ticket revenue concentrates, so that is where the asset gets built." },
        { kind: "p", text: "The next question is structural: organic depth versus the proximity-capped map pack, and what each one can and cannot do for you. Read [organic vs. the map pack](/playbook/organic-vs-the-map-pack) next, or run your own site through the [audit](/audit) and count how many of your pages answer a real long-tail query the considered buyer actually types." },
      ],
    },
  ],
};
